# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='/products'),
            preserve_default=False,
        ),
    ]
