# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(default=1, upload_to=products.models.image_upload_to),
            preserve_default=False,
        ),
    ]
