# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(upload_to=products.models.image_upload_to),
        ),
    ]
